# Limpeza do Dataset imoveis.csv
Notebook para avaliação, identificação de problemas e tratamento dos dados.

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Carregando dataset
file_path = "imoveis.csv"

try:
    df = pd.read_csv(file_path, sep=";", encoding="latin1")
except:
    df = pd.read_csv(file_path, sep=",", encoding="latin1")

df.head()

,id_imovel,id_proprietario,nome_proprietario,cpf,endereco,bairro,cidade,data_anuncio,tipo_imovel,metragem,quartos,banheiros,valor,valor_iptu,sistema_origem
0,1,P003,ANA PEREIRA,323.338.617-87,Rua W 167,Vila Mariana,Sao Paulo,09-01-2023,casa,165,3,1,729895,1212,Planilha
1,2,P003,Carla Dias,51025702129,Rua S 50,centro,Sao Paulo,05/01/2023,Loft,150,3,1,689004,3317,Planilha
2,3,P011,Ana Pereira,350.267.573-58,Rua V 84,Centro,Sao Paulo,2023-01-15,Loft,123m2,3,4,"1.790.113,00","5808,00",API
3,4,P009,CARLOS LIMA,64045862384,Rua H 36,Itaim,Sao Paulo,2023-01-31,Loft,-,1,2,2393927,"4258,00",Planilha
4,5,P008,Carla Dias,24345944431,Rua N 41,Itaim,Sao Paulo,2023/01/13,casa,-,2,1,1354507,594,API

In [3]:
# Análise inicial
print("Dimensões iniciais:", df.shape)
print("\nTipos de dados:\n", df.dtypes)
print("\nValores nulos:\n", df.isnull().sum())

Dimensões iniciais: (100, 15)

Tipos de dados:
 id_imovel             int64
id_proprietario      object
nome_proprietario    object
cpf                  object
endereco             object
bairro               object
cidade               object
data_anuncio         object
tipo_imovel          object
metragem             object
quartos              object
banheiros             int64
valor                object
valor_iptu           object
sistema_origem       object
dtype: object

Valores nulos:
 id_imovel             0
id_proprietario       0
nome_proprietario     0
cpf                   0
endereco              0
bairro                0
cidade                0
data_anuncio          0
tipo_imovel           0
metragem              0
quartos               0
banheiros             0
valor                 0
valor_iptu            0
sistema_origem       42
dtype: int64

In [4]:
# Remover duplicados
df = df.drop_duplicates()

# Padronizar nomes das colunas
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

# Remover espaços extras
for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].str.strip()

# Substituir valores vazios por NaN
df.replace(["", " ", "NA", "N/A", "null"], np.nan, inplace=True)

# Converter colunas numéricas possíveis
for col in df.columns:
    try:
        df[col] = pd.to_numeric(df[col])
    except:
        pass

# Remover registros com mais de 50% de nulos
df = df[df.isnull().mean(axis=1) < 0.5]

# Preencher nulos numéricos com mediana
for col in df.select_dtypes(include=["float64", "int64"]).columns:
    df[col] = df[col].fillna(df[col].median())

# Preencher nulos categóricos
for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].fillna("Não informado")

df.head()

,id_imovel,id_proprietario,nome_proprietario,cpf,endereco,bairro,cidade,data_anuncio,tipo_imovel,metragem,quartos,banheiros,valor,valor_iptu,sistema_origem
0,1,P003,ANA PEREIRA,323.338.617-87,Rua W 167,Vila Mariana,Sao Paulo,09-01-2023,casa,165,3,1,729895,1212,Planilha
1,2,P003,Carla Dias,51025702129,Rua S 50,centro,Sao Paulo,05/01/2023,Loft,150,3,1,689004,3317,Planilha
2,3,P011,Ana Pereira,350.267.573-58,Rua V 84,Centro,Sao Paulo,2023-01-15,Loft,123m2,3,4,"1.790.113,00","5808,00",API
3,4,P009,CARLOS LIMA,64045862384,Rua H 36,Itaim,Sao Paulo,2023-01-31,Loft,-,1,2,2393927,"4258,00",Planilha
4,5,P008,Carla Dias,24345944431,Rua N 41,Itaim,Sao Paulo,2023/01/13,casa,-,2,1,1354507,594,API

In [5]:
# Salvando dataset limpo
df.to_csv("imoveis_limpo.csv", index=False)

print("Arquivo imoveis_limpo.csv gerado com sucesso!")

Arquivo imoveis_limpo.csv gerado com sucesso!